import pandas as pd
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer
import pickle
import os

class FinancialQuantizer:
    def __init__(self, n_bins=256, rolling_vol_window=120):
        self.n_bins = n_bins
        self.rolling_vol_window = rolling_vol_window
        # We use quantile strategy for equal frequency binning (ensures balanced token classes)
        self.kbins = KBinsDiscretizer(n_bins=self.n_bins, encode='ordinal', strategy='quantile')
        self.is_fitted = False

    def calculate_features(self, df):
        """
        Calculate log-returns, rolling volatility, and time embeddings.
        Expects a DataFrame with columns: ['timestamp', 'open', 'high', 'low', 'close', 'volume']
        """
        df = df.copy()
        
        # 1. Log Returns
        df['log_return'] = np.log(df['close'] / df['close'].shift(1))
        
        # 2. Rolling Volatility
        df['rolling_vol'] = df['log_return'].rolling(window=self.rolling_vol_window).std()
        
        # 3. Normalized Return
        # Add a small epsilon to avoid division by zero during zero volatility
        df['norm_return'] = df['log_return'] / (df['rolling_vol'] + 1e-8)
        
        # 4. Time Embeddings
        # Ensure timestamp is datetime
        if not pd.api.types.is_datetime64_any_dtype(df['timestamp']):
            df['timestamp'] = pd.to_datetime(df['timestamp'])
            
        df['hour'] = df['timestamp'].dt.hour
        df['dayofweek'] = df['timestamp'].dt.dayofweek
        
        # Cyclic continuous time embeddings
        df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
        df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
        df['day_sin'] = np.sin(2 * np.pi * df['dayofweek'] / 7)
        df['day_cos'] = np.cos(2 * np.pi * df['dayofweek'] / 7)
        
        # 5. Exponential Moving Averages (EMA)
        ema12 = df['close'].ewm(span=12, adjust=False).mean()
        ema26 = df['close'].ewm(span=26, adjust=False).mean()
        df['ema12_dist'] = (df['close'] - ema12) / (ema12 + 1e-8)
        df['ema26_dist'] = (df['close'] - ema26) / (ema26 + 1e-8)
        
        # Drop NaN values generated by rolling window and shift
        df = df.dropna().reset_index(drop=True)
        return df

    def fit_transform(self, df):
        """Fit the quantizer to find bin edges and transform data into tokens."""
        df_feat = self.calculate_features(df)
        
        # Fit K-Bins on normalized returns
        tokens = self.kbins.fit_transform(df_feat[['norm_return']])
        df_feat['token'] = tokens.astype(int)
        
        self.is_fitted = True
        return df_feat

    def transform(self, df):
        """Transform new inference data using fitted bin edges."""
        if not self.is_fitted:
            raise ValueError("Quantizer must be fitted before calling transform.")
        
        df_feat = self.calculate_features(df)
        tokens = self.kbins.transform(df_feat[['norm_return']])
        df_feat['token'] = tokens.astype(int)
        
        return df_feat

    def save(self, filepath):
        """Save the fitted quantizer for use in inference."""
        with open(filepath, 'wb') as f:
            pickle.dump(self, f)

    @classmethod
    def load(cls, filepath):
        """Load a fitted quantizer."""
        with open(filepath, 'rb') as f:
            return pickle.load(f)

if __name__ == "__main__":
    print("Financial Quantizer Initialized.")
    print("Usage: Pass a Pandas DataFrame with OHLCV data to fit_transform().")
    
    # --- Example mock data usage ---
    # mock_data = pd.DataFrame({
    #     'timestamp': pd.date_range(start='2023-01-01', periods=2000, freq='1min'),
    #     'open': np.random.lognormal(0, 0.001, 2000).cumsum() + 1000,
    #     'high': np.random.lognormal(0, 0.001, 2000).cumsum() + 1005,
    #     'low': np.random.lognormal(0, 0.001, 2000).cumsum() + 995,
    #     'close': np.random.lognormal(0, 0.001, 2000).cumsum() + 1000,
    #     'volume': np.random.randint(100, 1000, 2000)
    # })
    # quantizer = FinancialQuantizer(n_bins=256, rolling_vol_window=120)
    # processed_df = quantizer.fit_transform(mock_data)
    # print(processed_df[['timestamp', 'close', 'log_return', 'rolling_vol', 'norm_return', 'token']].tail(10))
